[project]
name = 'Tokenized-Financial-Regulatory-Reporting-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.data-collection]
path = 'contracts/data-collection.clar'
clarity_version = 2
epoch = 2.5

[contracts.institution-verification]
path = 'contracts/institution-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.report-generation]
path = 'contracts/report-generation.clar'
clarity_version = 2
epoch = 2.5

[contracts.requirement-tracking]
path = 'contracts/requirement-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.submission-verification]
path = 'contracts/submission-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
